import { Milestone, MilestoneSnapshot } from "teleportal/protocol";

export interface MilestoneStorage {
  /**
   * Store a milestone into storage
   */
  createMilestone(ctx: {
    id: string; // TODO should the ID be generated by the client or DB?
    name: string;
    documentId: string;
    createdAt: number;
    snapshot: MilestoneSnapshot;
  }): Promise<void>;

  /**
   * Pull a milestone from storage
   */
  getMilestone(documentId: string, id: string): Promise<Milestone | null>;

  /**
   * Return the available milestones for a documentId (likely unloaded and metadata-only)
   */
  getMilestones(documentId: string): Promise<Milestone[]>;

  /**
   * Delete the specified milestones
   */
  deleteMilestone(documentId: string, id: string | string[]): Promise<void>;
}
